# Generated by Django 4.0 on 2022-03-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_email_avatar_email_first_name_email_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='avatar',
        ),
    ]
